version: 1
services:

    opencart:
        image: tutum/apache-php:opencart
        ports:
            - "80:80"
        links:
            - mysql
        restart: always

    mysql:
        image: mysql
            ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=opencart
        restart: always
